### ISSUE TITLE
typo in github link in package.json

### ISSUE THREAD

**Issue by seanzer** [zsxsoft/windows-caption-color#1]
[package.json](https://github.com/zsxsoft/windows-caption-color/blob/master/package.json#L11) has a typo. missing a `s` in `windows-caption-color`

**Comment by zsxsoft** [comment]
Sorry, I'll fix it in 2 weeks......

Date: Thu, 5 May 2016 07:11:22 -0700

**Comment by zsxsoft** [comment]
Solved in https://github.com/zsxsoft/windows-caption-color/commit/f9076e6e86b37b03c71321b84e24e995f3583bd9
